server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "GtDqIu4HSfeRbrCB3f172JKncOL8GFW1gJudpRI2wAVTX7xkuKjDziffzUi8wBmV"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds