spring:
  config:
    activate:
      on-profile: test

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: api-service
    server: http://test.api-service.local
    title: API Document
    version: 1.0.0